### ISSUE TITLE
Theme regions are named consistently with default base theme regions

### ISSUE THREAD

**Issue by pmackay** [civic-commons/opencivic#104] opened 2013-06-04 14:44 UTC
This means if starting with a fresh Omega theme, the context Features code will still position blocks correctly in most places. 

Worth reviewing if AdaptiveTheme has different naming to Omega for regions.

**Comment by sheldonrampton** [comment] 2013-06-16 14:17
Closing (duplicate of ticket #106)

**Closed as completed by sheldonrampton** 2013-06-16 14:17 UTC
