### ISSUE TITLE
Failed builds in jenkins

### ISSUE THREAD

**Issue by fusionx1** [civic-commons/opencivic#63] opened 2013-02-12 16:30 UTC
hi, i copied the transcript/logs of the latest failed build. 

https://gist.github.com/fusionx1/4771114

**Comment by pmackay** [comment] 2013-04-24 09:03
Is this still a problem?

**Comment by sheldonrampton** [comment] 2013-05-26 16:48
This is a duplicate of #84

**Closed as completed by sheldonrampton** 2013-05-26 16:48 UTC
